type Category {
  label: String
  value: String
  profiles: [Profile!] @relation
}

type Profile {
  netlifyID: ID!
  username: String!
  name: String!
  body: String!
  categories: [Category!] @relation
  profileImage: String
  website: String
  twitter: String
  facebook: String
  github: String
  instagram: String
}

type User {
  netlifyID: ID!
  stripeID: ID!
}

type Account {
  netlifyID: ID!
  stripeID: ID!
}

type Plan {
  netlifyID: ID!
  username: String
  name: String
  profileImage: String
  website: String
  twitter: String
  facebook: String
  github: String
  instagram: String
}

type Product {
  stripeID: ID!
  uuid: ID!
}

type Query {
  allCategories: [Category!]
  getProfileByNetlifyID(netlifyID: ID!): Profile

  getUserByNetlifyID(netlifyID: ID!): User!
  getUserByStripeID(stripeID: ID!): User!
  getAccountByNetlifyID(netlifyID: ID!): Account!
  getAccountByStripeID(stripeID: ID!): Account!
  getProductByUuid(uuid: ID!): Product!
  getProductByStripeID(stripeID: ID!): Product!
}