type Category {
  label: String
  value: String
  profiles: [Profile!] @relation
}

type Hashtag {
  label: String
  value: String
  icon: String
  products: [Product!] @relation
}

type Profile {
  netlifyID: ID!
  username: String!
  name: String!
  body: String!
  categories: [Category!] @relation
  profileImage: String
  website: String
  twitter: String
  facebook: String
  github: String
  instagram: String
  products: [Product!] @relation
}

type User {
  netlifyID: ID!
  stripeID: ID!
}

type Account {
  netlifyID: ID!
  stripeID: ID!
}

type Product {
  uuid: ID!
  netlifyID: ID!
  stripeID: ID
  title: String!
  body: String!
  description: String!
  interval: String!
  price: Int!
  status: String!
  author: Profile! @relation
  hashtags: [Hashtag!] @relation
}

type Query {
  allCategories: [Category!]
  allHashtags: [Hashtag!]
  getProfileByNetlifyID(netlifyID: ID!): Profile

  getUserByNetlifyID(netlifyID: ID!): User!
  getUserByStripeID(stripeID: ID!): User!
  getAccountByNetlifyID(netlifyID: ID!): Account!
  getAccountByStripeID(stripeID: ID!): Account!
  allProducts: [Product!]
  getProductByUuid(uuid: ID!): Product!
  getProductByStripeID(stripeID: ID!): Product!
}