backend:
  name: git-gateway
  branch: master
  accept_roles: #optional - accepts all users if left out
    - Admin
    - Mentor
# publish_mode: editorial_workflow

media_folder: client/static/img
public_folder: /img

collections:  
  - name: 'blog'
    label: 'Blog'
    description: >
      技術情報を共有するためのブログ。サポーターとしてのアピールや説明に利用してください。
    format: 'json'
    folder: 'client/content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: "Author", name: "authorId", widget: "relation", collection: "author", searchFields: ["title"], valueField: "{{slug}}", displayFields: ["{{title}} - {{username}}"] }

  - name: 'plan'
    identifier_field: '{{author}}-{{uuid}}'
    label: 'Plan'
    description: >
      ユーザーに販売するプランの詳細を登録します。
    format: 'json'
    folder: 'client/content/plan'
    create: true
    slug: '{{fields.uuid}}'
    editor:
      preview: false
    fields:
      - { label: 'UUID', name: 'uuid', widget: 'uuid' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - {
        label: "Hashtag",
        name: "hashtagIds",
        widget: "relation",
        collection: "settings",
        file: "hashtag", 
        searchFields: ["hashtags.*.value"],
        valueField: "hashtags.*.value",
        displayFields: ["hashtags.*.label"],
        multiple: true
      }
      - {
        label: "Price",
        name: "price",
        widget: "number",
        default: 100,
        valueType: "int",
        min: 100,
        max: 500000,
        step: 100,
        hint: 'Stripeで作成した金額'
      }
      - { label: "interval", name: "interval", widget: "select", options: [{label: "月額", value: "monthly"}, {label: "単発", value: "charge"}] }
      - { label: 'Body', name: 'body', widget: 'text' }
      - { label: "Author", name: "authorId", widget: "relation", collection: "author", searchFields: ["title"], valueField: "{{slug}}", displayFields: ["{{title}} - {{username}}"]}
      - { label: 'Status', name: 'status', widget: 'select', options: ["Active", "Hidden"] }

  - name: "author"
    identifier_field: username
    label: "Author"
    description: >
      サポーターのユーザー情報を登録します。自分の情報のみ更新するようにしてください。
    format: 'json'
    folder: "client/content/author"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Username", name: "username", widget: "string" }
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Profile Picture", name: "profilePicture", widget: "image" }
      - {
        label: "Category",
        name: "categoryIds",
        widget: "relation",
        collection: "settings",
        file: "category", 
        searchFields: ["categories.*.value"],
        valueField: "categories.*.value",
        displayFields: ["categories.*.label"],
        multiple: true
      }
      - { label: 'Body', name: 'body', widget: 'text' }
      - { label: "Website", name: "website", widget: "string", hint: 'ブログなどご自身のサイトのURLを記載', required: false }
      - { label: "Twitter", name: "twitter", widget: "string", hint: 'Twitterのユーザー名を指定してください', required: false }
      - { label: "Github", name: "github", widget: "string", hint: 'Githubのユーザー名を指定してください', required: false }
      - { label: "E-Mail", name: "email", widget: "string", hint: '問い合わせ先のメールアドレスを入力してください', required: false }

  - name: 'settings'
    label: 'Settings'
    format: 'json'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: 'category'
        label: 'Category'
        format: 'json'
        file: 'client/content/category.json'
        delete: false # Prevent users from deleting documents in this collection
        editor:
          preview: false
        fields:
          - name: categories
            label: Categories
            label_singular: 'Category'
            widget: list
            fields:
              - { label: 'Label', name: 'label', widget: 'string', hint: '表示する名称を記入' }
              - { label: 'Value', name: 'value', widget: 'string', hint: 'キャメル型の英数字で値を記入' }
              
      - name: 'hashtag'
        label: 'Hashtag'
        format: 'json'
        file: 'client/content/hashtag.json'
        fields:
          - name: hashtags
            label: Hashtags
            label_singular: 'Hashtag'
            widget: list
            fields:
              - { label: 'Label', name: 'label', widget: 'string', hint: '表示する名称を記入' }
              - { label: 'Value', name: 'value', widget: 'string', hint: 'キャメル型の英数字で値を記入' }
              - { label: "Icon", name: "icon", widget: "image", required: false }
